name: platzi-play-db
services:
  postgres:
    image: "postgres:latest"
    restart: unless-stopped
    environment:
      - "POSTGRES_DB=platzy_play_db"
      - "POSTGRES_PASSWORD=platzi-secret"
      - "POSTGRES_USER=platzi"
    ports:
      - 5431:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
